### ISSUE TITLE
Rebuilt LMDE 2 points to initrd.lz

### ISSUE THREAD

**Issue by Fred-Barclay** [rbern/debroot#1] opened 2016-09-15 20:21 UTC
G'day @rbern ! Thanks for this project - it's been a cool little programme to use. :smile: 

I have run into one issue I was hoping you could help with. I've been working on modifying a LMDE 2 iso (based on Debian 8). These are my steps:
1. Select Debian Jessie as the distro
2. Select the LMDE 2 mate iso (64-bit) to unsquash
3. Unsquash the iso to my build directory
4. Chroot a shell into the iso and install gnome-chess (small test project)
5. `exit` the shell
6. Build a ISO hybrid image that is UEFI enabled.

After this, I run into the following problem at boot:
`Loading /live/initrd.lz failed: No such file or directory`
Of course, being a Debian derivative, /live/initrd.lz doesn't exist; rather, it's /live/initrd.img. 

Looking at your source code, it appears that you do set the initrd image as `intrd.img` for debian distros, in DebrootForm.pm (line 1430). With that in mind, I can't figure out why it is apparently being pointed to the (nonexistent) initrd.lz file instead of initrd.img. 

Thanks for any help!
Fred

**Comment by rbern** [comment] 2016-09-16 03:07
Hi Fred,

I had never tested debroot with LMDE, so I followed your steps to reproduce the error.

I noticed that, upon the build, there was an error when the kernel was supposed to be re-installed (to rebuild initrd.img or initrd.lz). The error was that the kernel package couldn't be found/downloaded. The build process continues (it should stop), but the binary iso does not have any vmlinuz nor initrd.img/initrd.lz in it, so it doesn't boot.

The problem seems to be that the APT cache in the LMDE Live iso is very old and is not valid anymore (LMDE was released in 2015, there were many updated packages in the meantime), and that's why the kernel package was not found, downloaded and installed.

To fix this I've restarted debroot again, then I've typed the directory where the original iso file was unsquashed, then I've clicked the "**sources.list/upgrade**" tab and clicked the "**Update**" button. Then I've clicked the "Build" tab, then "Refresh options" and finally "Build ISO". The kernel was installed this time and the files vmlinuz/initrd.img were present in the /live/ directory, so the image should boot. It's not vmlinuz/initrd.lz like in the original iso but it should work.

In your case I would try to click the "sources.list/upgrade" tab and click the "Update" button between steps 3 and 4 or between steps 5 and 6. Can you please try and say if this workaround worked for you?

Because LMDE is different from the other debian derivatives (uses lzma compression) this will take some time to fix this in debroot (I'll try next week, when I have time).

Cheers!
Rui Bernardo

**Comment by Fred-Barclay** [comment] 2016-09-16 03:19
Hi Rui, 
Would you believe it, you hit on the step I forgot to mention? (Oops). I actually had clicked on "Update" between steps 3 and 4. 
Also when building, the kernel did download and install properly (since I had clicked Update).

So I was mistaken in my initial post:
(a). I clicked "Update" between steps 3 and 4.
(b). You are right; LMDE uses initrd.lz (I had thought it was initrd.img) but the rebuilt iso uses initrd.img. The rebuild iso does not boot. Perhaps there's something in LMDE's boot script that points to initrd.lz; since it doesn't exist in the rebuilt iso that explains why it refuses to boot. :)

Thanks!
BTW: I'm not a perl programmer, but if I figure out something before you do (unlikely) would you like me to send it in as a pull request?

**Comment by rbern** [comment] 2016-09-16 03:52
No, I was mistaken! I just tried to boot the image and the error is the one you've got in the first place. (points to initrd.lz)

The workaround is to edit grub and syslinux boot entry and replace ".lz" with ".img" in the boot options. The image then boots just fine.

You can make this change permanently if, before clicking "Build ISO", you change yourself manually the files grub.cfg and isolinux.xfg that are in /boot/grub/ and /isolinux/ in the *-binary directory. Then build the image in debroot with those files changed.

This was my first program in perl (I was doing it just to get the hands in perl and QT), so if you get this fixed in someway please do a pull request, I'll be glad to add it, if it works for all distros :)

**Closed** 2016-09-21 02:15 UTC

**Comment by Fred-Barclay** [comment] 2016-10-01 13:50
Thank you!
Sorry for the late reply - I've had some computer and Internet troubles so I haven't been able to test it yet.

**Comment by rbern** [comment] 2016-10-01 20:43
Hey Fred,
I've tested myself both LMDE2 and regular ubuntu Linuxmint and all seemed to work.
Thank you for making me fix this issue. Now this app really does what is says it does: rebuild debian and ubuntu Live isos and their derivatives.
Cheers!
